/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicalLogsRouteImport } from './routes/medical-logs'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SignInRouteImport } from './routes/SignIn'
import { Route as ExamplesRouteImport } from './routes/Examples'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimalsIndexRouteImport } from './routes/animals/index'
import { Route as AnimalsAddRouteImport } from './routes/animals/add'
import { Route as AnimalsAnimalIdRouteImport } from './routes/animals/$animalId'
import { Route as ProtectedAdminPortalRouteImport } from './routes/_protected/admin-portal'

const MedicalLogsRoute = MedicalLogsRouteImport.update({
  id: '/medical-logs',
  path: '/medical-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/SignIn',
  path: '/SignIn',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/Examples',
  path: '/Examples',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsAddRoute = AnimalsAddRouteImport.update({
  id: '/animals/add',
  path: '/animals/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsAnimalIdRoute = AnimalsAnimalIdRouteImport.update({
  id: '/animals/$animalId',
  path: '/animals/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminPortalRoute = ProtectedAdminPortalRouteImport.update({
  id: '/admin-portal',
  path: '/admin-portal',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Examples': typeof ExamplesRoute
  '/SignIn': typeof SignInRoute
  '/medical-logs': typeof MedicalLogsRoute
  '/admin-portal': typeof ProtectedAdminPortalRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals/add': typeof AnimalsAddRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Examples': typeof ExamplesRoute
  '/SignIn': typeof SignInRoute
  '/medical-logs': typeof MedicalLogsRoute
  '/admin-portal': typeof ProtectedAdminPortalRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals/add': typeof AnimalsAddRoute
  '/animals': typeof AnimalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Examples': typeof ExamplesRoute
  '/SignIn': typeof SignInRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/medical-logs': typeof MedicalLogsRoute
  '/_protected/admin-portal': typeof ProtectedAdminPortalRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals/add': typeof AnimalsAddRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Examples'
    | '/SignIn'
    | '/medical-logs'
    | '/admin-portal'
    | '/animals/$animalId'
    | '/animals/add'
    | '/animals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Examples'
    | '/SignIn'
    | '/medical-logs'
    | '/admin-portal'
    | '/animals/$animalId'
    | '/animals/add'
    | '/animals'
  id:
    | '__root__'
    | '/'
    | '/Examples'
    | '/SignIn'
    | '/_protected'
    | '/medical-logs'
    | '/_protected/admin-portal'
    | '/animals/$animalId'
    | '/animals/add'
    | '/animals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesRoute: typeof ExamplesRoute
  SignInRoute: typeof SignInRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  MedicalLogsRoute: typeof MedicalLogsRoute
  AnimalsAnimalIdRoute: typeof AnimalsAnimalIdRoute
  AnimalsAddRoute: typeof AnimalsAddRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medical-logs': {
      id: '/medical-logs'
      path: '/medical-logs'
      fullPath: '/medical-logs'
      preLoaderRoute: typeof MedicalLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SignIn': {
      id: '/SignIn'
      path: '/SignIn'
      fullPath: '/SignIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Examples': {
      id: '/Examples'
      path: '/Examples'
      fullPath: '/Examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/add': {
      id: '/animals/add'
      path: '/animals/add'
      fullPath: '/animals/add'
      preLoaderRoute: typeof AnimalsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$animalId': {
      id: '/animals/$animalId'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AnimalsAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin-portal': {
      id: '/_protected/admin-portal'
      path: '/admin-portal'
      fullPath: '/admin-portal'
      preLoaderRoute: typeof ProtectedAdminPortalRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminPortalRoute: typeof ProtectedAdminPortalRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminPortalRoute: ProtectedAdminPortalRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesRoute: ExamplesRoute,
  SignInRoute: SignInRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  MedicalLogsRoute: MedicalLogsRoute,
  AnimalsAnimalIdRoute: AnimalsAnimalIdRoute,
  AnimalsAddRoute: AnimalsAddRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
