export const mockAnimals = [
  {
    id: '1',
    name: 'Chewy',
    species: 'dog',
    breed: 'Labrador Retriever',
    sex: 'male',
    dob: '2016-09-15',
    status: 'available',
    intakeDate: '2024-01-10',
    description: 'Friendly and energetic dog who loves fetch and long walks.',
  },
  {
    id: '2',
    name: 'Bailey',
    species: 'dog',
    breed: 'Golden Retriever',
    sex: 'female',
    dob: '2019-12-26',
    status: 'foster',
    intakeDate: '2024-02-14',
    description: 'Gentle and calm, great with kids and other dogs.',
  },
  {
    id: '3',
    name: 'Luna',
    species: 'cat',
    breed: 'Domestic Shorthair',
    sex: 'female',
    dob: '2021-03-05',
    status: 'available',
    intakeDate: '2024-03-01',
    description: 'Curious and independent, enjoys sunny windowsills.',
  },
  {
    id: '4',
    name: 'Max',
    species: 'dog',
    breed: 'Border Collie',
    sex: 'male',
    dob: '2020-07-18',
    status: 'adopted',
    intakeDate: '2023-11-20',
    description: 'Highly intelligent and eager to please. Needs active home.',
  },
  {
    id: '5',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Maine Coon',
    sex: 'male',
    dob: '2018-05-22',
    status: 'quarantine',
    intakeDate: '2024-04-05',
    description: 'Large fluffy cat, very affectionate once he warms up.',
  },
  {
    id: '6',
    name: 'Daisy',
    species: 'dog',
    breed: 'Beagle',
    sex: 'female',
    dob: '2022-01-30',
    status: 'available',
    intakeDate: '2024-04-12',
    description: 'Playful and curious, loves sniffing everything on walks.',
  },
  {
    id: '7',
    name: 'Shadow',
    species: 'cat',
    breed: 'Russian Blue',
    sex: 'male',
    dob: '2020-11-11',
    status: 'foster',
    intakeDate: '2024-01-28',
    description: 'Quiet and reserved, bonds deeply with his caregiver.',
  },
  {
    id: '8',
    name: 'Buddy',
    species: 'dog',
    breed: 'Poodle Mix',
    sex: 'male',
    dob: '2023-03-03',
    status: 'available',
    intakeDate: '2024-05-01',
    description: 'Young and playful, still learning basic commands.',
  },
  {
    id: '9',
    name: 'Nala',
    species: 'cat',
    breed: 'Siamese',
    sex: 'female',
    dob: '2019-08-14',
    status: 'adopted',
    intakeDate: '2023-09-15',
    description: 'Vocal and social, loves being the center of attention.',
  },
  {
    id: '10',
    name: 'Biscuit',
    species: 'other',
    breed: 'Holland Lop',
    sex: 'female',
    dob: '2022-06-20',
    status: 'available',
    intakeDate: '2024-03-22',
    description: 'Friendly rabbit, enjoys being held and fresh vegetables.',
  },
];
